import { PrismaClient, Prisma } from "@prisma/client";

const updateUserById = async (
  id: string,
  updatedUser: Prisma.UserUpdateInput // Type generated by Prisma representing the allowed update fields for the User model
) => {
  const prisma = new PrismaClient();
  const user = await prisma.user.updateMany({
    where: { id },
    data: updatedUser,
  });
  return user.count > 0 ? id : null;
};

export default updateUserById;
